sudo: required

# NOTE: It is necessary to explicitly set the distribution to "trusty" due to
# the complex 'matrix: include:' logic below
# More information: https://github.com/travis-ci/travis-ci/issues/5448
dist: trusty

addons:
  postgresql: "9.4"

services:
  - docker
  - postgresql
  - elasticsearch

language: python

env:
  global:
    - RESOLWE_POSTGRESQL_USER=postgres
    - RESOLWE_POSTGRESQL_PORT=5432
    - RESOLWE_ES_PORT=9200
    # XXX: Work-around for the "No module named 'six'" issue with the latest
    # version of setuptools (36.0.0):
    # https://github.com/pypa/setuptools/issues/1042
    - VIRTUALENV_NO_DOWNLOAD=1

# NOTE: Explicit Python versions make Travis job description more informative
matrix:
  include:
    - env: TOX_ENV=py27
      python: "2.7"
    - env: TOX_ENV=py34
      python: "3.4"
    - env: TOX_ENV=py35
      python: "3.5"
    - env: TOX_ENV=docs
      python: "3.5"
    - env: TOX_ENV=linters
      python: "3.5"
    - env: TOX_ENV=packaging
      python: "3.5"

before_install:
  # Manually install Elastic Search.
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.3/elasticsearch-2.4.3.deb
  - sudo dpkg -i --force-confnew elasticsearch-2.4.3.deb
  - sudo service elasticsearch restart

install: pip install tox

script: tox -e $TOX_ENV

after_success:
 - pip install codecov
 - codecov -e TOX_ENV
